FROM python:3.8-slim
LABEL Author="Prashanna" Description="User management docker image"

WORKDIR /code
COPY setup.* /code/
COPY src/ /code/src/

RUN chmod 755 setup.sh &&\
    ./setup.sh

COPY src/user_management /code/app/
EXPOSE 80
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]