---
version: "3.2"
services:
  openapi:
    image: "openapitools/openapi-generator-cli:v4.3.1"
    user: "${UID}:${GID}"
    volumes:
      - .:/local
    working_dir: /local
  pgadmin_local:
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@email.com
      - PGADMIN_DEFAULT_PASSWORD=xxxx
    image: "dpage/pgadmin4:latest"
    ports:
      - 8080:80
  postgres_local:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    image: "postgres:12.2-alpine"
    ports:
      - 5432:5432
  speccy:
    image: "wework/speccy:3c3bec7"
    volumes:
      - .:/project:rw