# coding: utf-8

"""
    User Management Microservice

    User Management Microservice  # noqa: E501

    The version of the OpenAPI document: v1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from user_management_client_v1.configuration import Configuration


class GetUsersResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'users': 'list[User]',
        'page': 'int',
        'page_size': 'int',
        'total_count': 'int'
    }

    attribute_map = {
        'users': 'users',
        'page': 'page',
        'page_size': 'pageSize',
        'total_count': 'totalCount'
    }

    def __init__(self, users=None, page=None, page_size=None, total_count=None, local_vars_configuration=None):  # noqa: E501
        """GetUsersResponse - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._users = None
        self._page = None
        self._page_size = None
        self._total_count = None
        self.discriminator = None

        if users is not None:
            self.users = users
        if page is not None:
            self.page = page
        if page_size is not None:
            self.page_size = page_size
        if total_count is not None:
            self.total_count = total_count

    @property
    def users(self):
        """Gets the users of this GetUsersResponse.  # noqa: E501


        :return: The users of this GetUsersResponse.  # noqa: E501
        :rtype: list[User]
        """
        return self._users

    @users.setter
    def users(self, users):
        """Sets the users of this GetUsersResponse.


        :param users: The users of this GetUsersResponse.  # noqa: E501
        :type: list[User]
        """

        self._users = users

    @property
    def page(self):
        """Gets the page of this GetUsersResponse.  # noqa: E501


        :return: The page of this GetUsersResponse.  # noqa: E501
        :rtype: int
        """
        return self._page

    @page.setter
    def page(self, page):
        """Sets the page of this GetUsersResponse.


        :param page: The page of this GetUsersResponse.  # noqa: E501
        :type: int
        """

        self._page = page

    @property
    def page_size(self):
        """Gets the page_size of this GetUsersResponse.  # noqa: E501


        :return: The page_size of this GetUsersResponse.  # noqa: E501
        :rtype: int
        """
        return self._page_size

    @page_size.setter
    def page_size(self, page_size):
        """Sets the page_size of this GetUsersResponse.


        :param page_size: The page_size of this GetUsersResponse.  # noqa: E501
        :type: int
        """

        self._page_size = page_size

    @property
    def total_count(self):
        """Gets the total_count of this GetUsersResponse.  # noqa: E501


        :return: The total_count of this GetUsersResponse.  # noqa: E501
        :rtype: int
        """
        return self._total_count

    @total_count.setter
    def total_count(self, total_count):
        """Sets the total_count of this GetUsersResponse.


        :param total_count: The total_count of this GetUsersResponse.  # noqa: E501
        :type: int
        """

        self._total_count = total_count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetUsersResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, GetUsersResponse):
            return True

        return self.to_dict() != other.to_dict()
