# coding: utf-8

"""
    User Management Microservice

    User Management Microservice  # noqa: E501

    The version of the OpenAPI document: v1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import user_management_client_v1
from user_management_client_v1.models.get_users_response import GetUsersResponse  # noqa: E501
from user_management_client_v1.rest import ApiException

class TestGetUsersResponse(unittest.TestCase):
    """GetUsersResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test GetUsersResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = user_management_client_v1.models.get_users_response.GetUsersResponse()  # noqa: E501
        if include_optional :
            return GetUsersResponse(
                users = [
                    user_management_client_v1.models.user.User(
                        date_of_birth = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        gender = 'MALE', 
                        is_active = True, 
                        email = '0', 
                        first_name = '0', 
                        id = 'a', 
                        last_name = '0', )
                    ], 
                page = 56, 
                page_size = 56, 
                total_count = 56
            )
        else :
            return GetUsersResponse(
        )

    def testGetUsersResponse(self):
        """Test GetUsersResponse"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
