# coding: utf-8

"""
    User Management Microservice

    User Management Microservice  # noqa: E501

    The version of the OpenAPI document: v1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import user_management_client_v1
from user_management_client_v1.models.gender import Gender  # noqa: E501
from user_management_client_v1.rest import ApiException

class TestGender(unittest.TestCase):
    """Gender unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Gender
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = user_management_client_v1.models.gender.Gender()  # noqa: E501
        if include_optional :
            return Gender(
            )
        else :
            return Gender(
        )

    def testGender(self):
        """Test Gender"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
