"""add_gender_column

Revision ID: b484d36ef34b
Revises: ea86be36e21f
Create Date: 2022-08-20 09:54:12.050680

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql



# revision identifiers, used by Alembic.
revision = 'b484d36ef34b'
down_revision = 'ea86be36e21f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    gender = postgresql.ENUM('MALE', 'FEMALE', 'OTHER', name='gender')
    gender.create(op.get_bind())

    op.add_column('user', sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'gender')

    gender = postgresql.ENUM('MALE', 'FEMALE', 'OTHER', name='gender')
    gender.drop(op.get_bind())
    # ### end Alembic commands ###
